// Generated by Selenium IDE

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class BlindPeopleTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    [Obsolete]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor) driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void BlindPeople()
    {
        driver.Navigate().GoToUrl("https://uomgol3.by/");

        driver.FindElement(By.CssSelector(".glyphicon-eye-open")).Click();
        driver.FindElement(By.CssSelector(".option:nth-child(2) button:nth-child(4) > i")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(2) button:nth-child(3) > i")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(2) button:nth-child(2) > i")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(2) button:nth-child(1) > i")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(1) button:nth-child(4) > span")).Click();
        driver.FindElement(By.CssSelector(".active_option:nth-child(4) > span")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".active_option:nth-child(4) > span"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.CssSelector(".active_option:nth-child(4) > span")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(1) button:nth-child(2) > span")).Click();
        driver.FindElement(By.CssSelector(".panel_bar .option:nth-child(1) button:nth-child(3)")).Click();
        driver.FindElement(By.CssSelector(".icon-eye-slash")).Click();
    }
}